#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

MASTER_REPO_URL=""
MASTER_BRANCH=""
MASTER_TARGET_DIR=""
SUB_REPO_URL1=""
SUB_BRANCH1=""
SUB_TARGET_DIR1=""
SUB_REPO_URL2=""
SUB_BRANCH2=""
SUB_TARGET_DIR2=""
SKIP_SYNC=0
GENERATE_ECLIPSE_PROJECTS=0
IMPORT_INTO_ECLIPSE=0
COMPOSE_SERVICE="eclipse"
REPOS_DIR="${REPO_ROOT}/portable/repos"
WORKSPACE_DIR="${REPO_ROOT}/portable/workspace"

usage() {
  cat <<'EOF'
Usage:
  shared/scripts/setup-projects.sh \
    --master-repo-url <url> \
    [--master-branch <branch>] \
    [--master-target-dir <dir>] \
    [--sub-repo-url1 <url>] \
    [--sub-branch1 <branch>] \
    [--sub-target-dir1 <dir>] \
    [--sub-repo-url2 <url>] \
    [--sub-branch2 <branch>] \
    [--sub-target-dir2 <dir>] \
    [--skip-sync] \
    [--generate-eclipse-projects] \
    [--import-into-eclipse] \
    [--compose-service <name>] \
    [--repos-dir <path>] \
    [--workspace-dir <path>]
EOF
}

default_target_dir() {
  local repo_url="$1"
  local leaf="${repo_url##*/}"
  leaf="${leaf%.git}"
  printf '%s\n' "${leaf}"
}

write_manifest() {
  local manifest_path="${REPO_ROOT}/repos-manifest.txt"
  {
    echo "# Format: <git-url>|<branch>|<target-subdir-under-repos>"
    echo "# Generated by shared/scripts/setup-projects.sh"
    echo
    [[ -n "${MASTER_REPO_URL}" ]] && echo "${MASTER_REPO_URL}|${MASTER_BRANCH}|${MASTER_TARGET_DIR}"
    [[ -n "${SUB_REPO_URL1}" ]] && echo "${SUB_REPO_URL1}|${SUB_BRANCH1}|${SUB_TARGET_DIR1}"
    [[ -n "${SUB_REPO_URL2}" ]] && echo "${SUB_REPO_URL2}|${SUB_BRANCH2}|${SUB_TARGET_DIR2}"
  } > "${manifest_path}"
  echo "Manifest written: ${manifest_path}"
}

branch_exists_local() {
  local repo_path="$1"
  local branch="$2"
  git -C "${repo_path}" show-ref --verify --quiet "refs/heads/${branch}"
}

branch_exists_remote() {
  local repo_path="$1"
  local branch="$2"
  git -C "${repo_path}" show-ref --verify --quiet "refs/remotes/origin/${branch}"
}

origin_default_branch() {
  local repo_path="$1"
  local ref
  ref="$(git -C "${repo_path}" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null || true)"
  ref="${ref#origin/}"
  printf '%s\n' "${ref}"
}

resolve_branch() {
  local repo_path="$1"
  local requested="$2"

  if [[ -n "${requested}" ]]; then
    if branch_exists_local "${repo_path}" "${requested}" || branch_exists_remote "${repo_path}" "${requested}"; then
      printf '%s\n' "${requested}"
      return
    fi
    local fallback
    fallback="$(origin_default_branch "${repo_path}")"
    if [[ -n "${fallback}" ]] && (branch_exists_local "${repo_path}" "${fallback}" || branch_exists_remote "${repo_path}" "${fallback}"); then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to '${fallback}'." >&2
      printf '%s\n' "${fallback}"
      return
    fi
    if branch_exists_local "${repo_path}" "master" || branch_exists_remote "${repo_path}" "master"; then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to 'master'." >&2
      printf '%s\n' "master"
      return
    fi
    if branch_exists_local "${repo_path}" "main" || branch_exists_remote "${repo_path}" "main"; then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to 'main'." >&2
      printf '%s\n' "main"
      return
    fi
    echo "ERROR: Cannot resolve branch for ${repo_path}" >&2
    exit 1
  fi

  local current
  current="$(git -C "${repo_path}" branch --show-current 2>/dev/null || true)"
  if [[ -n "${current}" ]]; then
    printf '%s\n' "${current}"
    return
  fi

  local origin_default
  origin_default="$(origin_default_branch "${repo_path}")"
  if [[ -n "${origin_default}" ]]; then
    printf '%s\n' "${origin_default}"
    return
  fi

  if branch_exists_local "${repo_path}" "master" || branch_exists_remote "${repo_path}" "master"; then
    printf '%s\n' "master"
    return
  fi
  if branch_exists_local "${repo_path}" "main" || branch_exists_remote "${repo_path}" "main"; then
    printf '%s\n' "main"
    return
  fi
  printf '%s\n' ""
}

clone_or_update_repo() {
  local repo_url="$1"
  local branch="$2"
  local target="$3"
  local target_path="${REPOS_DIR}/${target}"

  mkdir -p "${REPOS_DIR}"

  if [[ ! -d "${target_path}" ]]; then
    echo "Cloning ${repo_url} -> ${target_path}"
    git clone --recurse-submodules "${repo_url}" "${target_path}"
  else
    if [[ ! -d "${target_path}/.git" ]]; then
      echo "ERROR: Target exists but is not a git repository: ${target_path}" >&2
      exit 1
    fi
    echo "Updating existing repo: ${target_path}"
    git -C "${target_path}" fetch --all --prune
    git -C "${target_path}" submodule update --init --recursive
  fi

  local effective_branch
  effective_branch="$(resolve_branch "${target_path}" "${branch}")"
  if [[ -n "${effective_branch}" ]]; then
    echo "Checking out branch '${effective_branch}' in ${target_path}"
    if branch_exists_local "${target_path}" "${effective_branch}"; then
      git -C "${target_path}" checkout "${effective_branch}"
    else
      git -C "${target_path}" checkout -b "${effective_branch}" --track "origin/${effective_branch}"
    fi
    git -C "${target_path}" pull --ff-only origin "${effective_branch}"
    git -C "${target_path}" submodule update --init --recursive
  else
    echo "WARN: No branch resolved for ${target_path}. Keeping current HEAD."
  fi
}

generate_eclipse_metadata_for_repo() {
  local repo_path="$1"
  local gradlew=""

  if [[ -x "${repo_path}/gradlew" ]]; then
    gradlew="${repo_path}/gradlew"
  else
    local child
    while IFS= read -r -d '' child; do
      gradlew="${child}"
      break
    done < <(find "${repo_path}" -mindepth 2 -maxdepth 2 -type f -name gradlew -perm -u+x -print0 2>/dev/null)
  fi

  if [[ -z "${gradlew}" ]]; then
    echo "WARN: No executable gradlew found in ${repo_path}. Skipping Eclipse metadata generation."
    return
  fi

  local workdir
  workdir="$(dirname "${gradlew}")"
  echo "Generating Eclipse metadata via ${gradlew}"
  (cd "${workdir}" && ./gradlew -q eclipse)
}

run_docker_import() {
  mkdir -p "${WORKSPACE_DIR}"
  local egit_hidden="${WORKSPACE_DIR}/.metadata/.plugins/org.eclipse.core.resources/.projects/.org.eclipse.egit.core.cmp"
  mkdir -p "${egit_hidden}"
  local list_file="${WORKSPACE_DIR}/.eclipse-import-paths.txt"
  local imported_file="${WORKSPACE_DIR}/.eclipse-import-projects.txt"

  project_name_from_path() {
    basename "$1"
  }

  collect_workspace_project_names() {
    local projects_dir="${WORKSPACE_DIR}/.metadata/.plugins/org.eclipse.core.resources/.projects"
    if [[ ! -d "${projects_dir}" ]]; then
      return
    fi
    find "${projects_dir}" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' \
      | grep -v '^\.' \
      | sort -u
  }

  collect_expected_project_paths() {
    find "${REPOS_DIR}" -type f -name .project -printf '%h\n' | sort -u
  }

  missing_workspace_projects() {
    local expected_list="$1"
    local workspace_list="$2"
    comm -23 <(printf '%s\n' "${expected_list}" | sed '/^$/d' | sort -u) <(printf '%s\n' "${workspace_list}" | sed '/^$/d' | sort -u)
  }

  local import_count=0
  : > "${list_file}"
  : > "${imported_file}"
  local host_real
  host_real="$(cd "${REPOS_DIR}" && pwd)"
  mapfile -t host_project_dirs < <(collect_expected_project_paths)
  for project_dir in "${host_project_dirs[@]}"; do
    local rel="${project_dir#${host_real}/}"
    printf '/repos/%s\n' "${rel}" >> "${list_file}"
    printf '%s\n' "$(project_name_from_path "${project_dir}")" >> "${imported_file}"
    import_count=$((import_count + 1))
  done

  if [[ "${import_count}" -eq 0 ]]; then
    echo "No .project files found under ${REPOS_DIR}. Nothing to import."
    return
  fi

  echo "Prepared Docker Eclipse import list: ${list_file} (${import_count} projects via headless -import)"

  echo "Stopping compose service '${COMPOSE_SERVICE}' for exclusive workspace access..."
  docker compose stop "${COMPOSE_SERVICE}" >/dev/null 2>&1 || true

  local headless_cmd='set -euo pipefail
xv=""
cleanup() {
  if [ -n "${xv:-}" ] && kill -0 "$xv" >/dev/null 2>&1; then
    kill "$xv" >/dev/null 2>&1 || true
    wait "$xv" 2>/dev/null || true
  fi
}
trap cleanup EXIT
Xvfb :99 -screen 0 1920x1080x24 >/tmp/xvfb.log 2>&1 &
xv=$!
export DISPLAY=:99
while IFS= read -r p; do
  [ -z "$p" ] && continue
  echo "IMPORT:$p"
  code=0
  timeout 40 /opt/eclipse/eclipse -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /workspace -import "$p" || code=$?
  if [ "$code" -ne 0 ] && [ "$code" -ne 124 ]; then
    echo "FAILED:$p:$code"
    exit "$code"
  fi
done < /workspace/.eclipse-import-paths.txt'

  echo "Running headless Eclipse import in one Docker run..."
  docker compose run --rm --no-deps --entrypoint /bin/bash -e USE_HOST_X11=0 "${COMPOSE_SERVICE}" -lc "${headless_cmd}"

  local expected_names
  local workspace_names
  local missing_names
  expected_names="$(sed '/^$/d' "${imported_file}" | sort -u)"
  workspace_names="$(collect_workspace_project_names)"
  missing_names="$(missing_workspace_projects "${expected_names}" "${workspace_names}")"

  if [[ -n "${missing_names}" ]]; then
    echo "Detected missing Eclipse workspace projects after bulk import:"
    while IFS= read -r missing_name; do
      [[ -z "${missing_name}" ]] && continue
      printf '  %s\n' "${missing_name}"
    done <<< "${missing_names}"

    while IFS= read -r missing_name; do
      [[ -z "${missing_name}" ]] && continue

      local missing_path=""
      for project_dir in "${host_project_dirs[@]}"; do
        if [[ "$(project_name_from_path "${project_dir}")" == "${missing_name}" ]]; then
          missing_path="${project_dir}"
          break
        fi
      done

      if [[ -z "${missing_path}" ]]; then
        echo "WARN: Could not resolve project path for missing workspace project '${missing_name}'."
        continue
      fi

      local rel_missing="${missing_path#${host_real}/}"
      local single_import_cmd='set -euo pipefail
xv=""
cleanup() {
  if [ -n "${xv:-}" ] && kill -0 "$xv" >/dev/null 2>&1; then
    kill "$xv" >/dev/null 2>&1 || true
    wait "$xv" 2>/dev/null || true
  fi
}
trap cleanup EXIT
Xvfb :99 -screen 0 1920x1080x24 >/tmp/xvfb.log 2>&1 &
xv=$!
export DISPLAY=:99
timeout 60 /opt/eclipse/eclipse -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /workspace -import "/repos/'"${rel_missing}"'"'

      echo "Retrying missing project import: ${missing_name}"
      docker compose run --rm --no-deps --entrypoint /bin/bash -e USE_HOST_X11=0 "${COMPOSE_SERVICE}" -lc "${single_import_cmd}"
    done <<< "${missing_names}"

    workspace_names="$(collect_workspace_project_names)"
    missing_names="$(missing_workspace_projects "${expected_names}" "${workspace_names}")"
    if [[ -n "${missing_names}" ]]; then
      echo "ERROR: Eclipse workspace import still incomplete after retries:" >&2
      while IFS= read -r missing_name; do
        [[ -z "${missing_name}" ]] && continue
        printf '  %s\n' "${missing_name}" >&2
      done <<< "${missing_names}"
      return 1
    fi
  fi

  echo "Verified Eclipse workspace import completeness (${import_count} projects)."

  echo "Starting compose service '${COMPOSE_SERVICE}'..."
  REPOS_DIR="${REPOS_DIR}" WORKSPACE_DIR="${WORKSPACE_DIR}" docker compose up -d "${COMPOSE_SERVICE}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --master-repo-url) MASTER_REPO_URL="$2"; shift 2;;
    --master-branch) MASTER_BRANCH="$2"; shift 2;;
    --master-target-dir) MASTER_TARGET_DIR="$2"; shift 2;;
    --sub-repo-url1) SUB_REPO_URL1="$2"; shift 2;;
    --sub-branch1) SUB_BRANCH1="$2"; shift 2;;
    --sub-target-dir1) SUB_TARGET_DIR1="$2"; shift 2;;
    --sub-repo-url2) SUB_REPO_URL2="$2"; shift 2;;
    --sub-branch2) SUB_BRANCH2="$2"; shift 2;;
    --sub-target-dir2) SUB_TARGET_DIR2="$2"; shift 2;;
    --skip-sync) SKIP_SYNC=1; shift;;
    --generate-eclipse-projects) GENERATE_ECLIPSE_PROJECTS=1; shift;;
    --import-into-eclipse) IMPORT_INTO_ECLIPSE=1; shift;;
    --compose-service) COMPOSE_SERVICE="$2"; shift 2;;
    --repos-dir) REPOS_DIR="$2"; shift 2;;
    --workspace-dir) WORKSPACE_DIR="$2"; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1;;
  esac
done

if [[ -z "${MASTER_REPO_URL}" ]]; then
  echo "ERROR: --master-repo-url is required" >&2
  usage
  exit 1
fi

if [[ -z "${MASTER_TARGET_DIR}" ]]; then
  MASTER_TARGET_DIR="$(default_target_dir "${MASTER_REPO_URL}")"
fi
if [[ -n "${SUB_REPO_URL1}" && -z "${SUB_TARGET_DIR1}" ]]; then
  SUB_TARGET_DIR1="$(default_target_dir "${SUB_REPO_URL1}")"
fi
if [[ -n "${SUB_REPO_URL2}" && -z "${SUB_TARGET_DIR2}" ]]; then
  SUB_TARGET_DIR2="$(default_target_dir "${SUB_REPO_URL2}")"
fi

write_manifest

if [[ "${SKIP_SYNC}" -eq 0 ]]; then
  clone_or_update_repo "${MASTER_REPO_URL}" "${MASTER_BRANCH}" "${MASTER_TARGET_DIR}"
  if [[ -n "${SUB_REPO_URL1}" ]]; then
    clone_or_update_repo "${SUB_REPO_URL1}" "${SUB_BRANCH1}" "${SUB_TARGET_DIR1}"
  fi
  if [[ -n "${SUB_REPO_URL2}" ]]; then
    clone_or_update_repo "${SUB_REPO_URL2}" "${SUB_BRANCH2}" "${SUB_TARGET_DIR2}"
  fi
fi

if [[ "${GENERATE_ECLIPSE_PROJECTS}" -eq 1 ]]; then
  generate_eclipse_metadata_for_repo "${REPOS_DIR}/${MASTER_TARGET_DIR}"
  [[ -n "${SUB_REPO_URL1}" ]] && generate_eclipse_metadata_for_repo "${REPOS_DIR}/${SUB_TARGET_DIR1}"
  [[ -n "${SUB_REPO_URL2}" ]] && generate_eclipse_metadata_for_repo "${REPOS_DIR}/${SUB_TARGET_DIR2}"
fi

if [[ "${IMPORT_INTO_ECLIPSE}" -eq 1 ]]; then
  run_docker_import
fi

echo "Done. Repositories are managed via: ${REPO_ROOT}/repos-manifest.txt"
