#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

MASTER_REPO_URL=""
MASTER_BRANCH=""
MASTER_TARGET_DIR=""
SUB_REPO_URL1=""
SUB_BRANCH1=""
SUB_TARGET_DIR1=""
SUB_REPO_URL2=""
SUB_BRANCH2=""
SUB_TARGET_DIR2=""
SKIP_SYNC=0
GENERATE_ECLIPSE_PROJECTS=0
IMPORT_INTO_ECLIPSE=0
COMPOSE_SERVICE="eclipse"
REPOS_DIR="${REPO_ROOT}/repos"
WORKSPACE_DIR="${REPO_ROOT}/portable/workspace"

usage() {
  cat <<'EOF'
Usage:
  shared/scripts/setup-projects.sh \
    --master-repo-url <url> \
    [--master-branch <branch>] \
    [--master-target-dir <dir>] \
    [--sub-repo-url1 <url>] \
    [--sub-branch1 <branch>] \
    [--sub-target-dir1 <dir>] \
    [--sub-repo-url2 <url>] \
    [--sub-branch2 <branch>] \
    [--sub-target-dir2 <dir>] \
    [--skip-sync] \
    [--generate-eclipse-projects] \
    [--import-into-eclipse] \
    [--compose-service <name>] \
    [--repos-dir <path>] \
    [--workspace-dir <path>]
EOF
}

default_target_dir() {
  local repo_url="$1"
  local leaf="${repo_url##*/}"
  leaf="${leaf%.git}"
  printf '%s\n' "${leaf}"
}

write_manifest() {
  local manifest_path="${REPO_ROOT}/repos-manifest.txt"
  {
    echo "# Format: <git-url>|<branch>|<target-subdir-under-repos>"
    echo "# Generated by shared/scripts/setup-projects.sh"
    echo
    [[ -n "${MASTER_REPO_URL}" ]] && echo "${MASTER_REPO_URL}|${MASTER_BRANCH}|${MASTER_TARGET_DIR}"
    [[ -n "${SUB_REPO_URL1}" ]] && echo "${SUB_REPO_URL1}|${SUB_BRANCH1}|${SUB_TARGET_DIR1}"
    [[ -n "${SUB_REPO_URL2}" ]] && echo "${SUB_REPO_URL2}|${SUB_BRANCH2}|${SUB_TARGET_DIR2}"
  } > "${manifest_path}"
  echo "Manifest written: ${manifest_path}"
}

branch_exists_local() {
  local repo_path="$1"
  local branch="$2"
  git -C "${repo_path}" show-ref --verify --quiet "refs/heads/${branch}"
}

branch_exists_remote() {
  local repo_path="$1"
  local branch="$2"
  git -C "${repo_path}" show-ref --verify --quiet "refs/remotes/origin/${branch}"
}

origin_default_branch() {
  local repo_path="$1"
  local ref
  ref="$(git -C "${repo_path}" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null || true)"
  ref="${ref#origin/}"
  printf '%s\n' "${ref}"
}

resolve_branch() {
  local repo_path="$1"
  local requested="$2"

  if [[ -n "${requested}" ]]; then
    if branch_exists_local "${repo_path}" "${requested}" || branch_exists_remote "${repo_path}" "${requested}"; then
      printf '%s\n' "${requested}"
      return
    fi
    local fallback
    fallback="$(origin_default_branch "${repo_path}")"
    if [[ -n "${fallback}" ]] && (branch_exists_local "${repo_path}" "${fallback}" || branch_exists_remote "${repo_path}" "${fallback}"); then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to '${fallback}'." >&2
      printf '%s\n' "${fallback}"
      return
    fi
    if branch_exists_local "${repo_path}" "master" || branch_exists_remote "${repo_path}" "master"; then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to 'master'." >&2
      printf '%s\n' "master"
      return
    fi
    if branch_exists_local "${repo_path}" "main" || branch_exists_remote "${repo_path}" "main"; then
      echo "WARN: Requested branch '${requested}' not found in ${repo_path}. Falling back to 'main'." >&2
      printf '%s\n' "main"
      return
    fi
    echo "ERROR: Cannot resolve branch for ${repo_path}" >&2
    exit 1
  fi

  local current
  current="$(git -C "${repo_path}" branch --show-current 2>/dev/null || true)"
  if [[ -n "${current}" ]]; then
    printf '%s\n' "${current}"
    return
  fi

  local origin_default
  origin_default="$(origin_default_branch "${repo_path}")"
  if [[ -n "${origin_default}" ]]; then
    printf '%s\n' "${origin_default}"
    return
  fi

  if branch_exists_local "${repo_path}" "master" || branch_exists_remote "${repo_path}" "master"; then
    printf '%s\n' "master"
    return
  fi
  if branch_exists_local "${repo_path}" "main" || branch_exists_remote "${repo_path}" "main"; then
    printf '%s\n' "main"
    return
  fi
  printf '%s\n' ""
}

clone_or_update_repo() {
  local repo_url="$1"
  local branch="$2"
  local target="$3"
  local target_path="${REPOS_DIR}/${target}"

  mkdir -p "${REPOS_DIR}"

  if [[ ! -d "${target_path}" ]]; then
    echo "Cloning ${repo_url} -> ${target_path}"
    git clone --recurse-submodules "${repo_url}" "${target_path}"
  else
    if [[ ! -d "${target_path}/.git" ]]; then
      echo "ERROR: Target exists but is not a git repository: ${target_path}" >&2
      exit 1
    fi
    echo "Updating existing repo: ${target_path}"
    git -C "${target_path}" fetch --all --prune
    git -C "${target_path}" submodule update --init --recursive
  fi

  local effective_branch
  effective_branch="$(resolve_branch "${target_path}" "${branch}")"
  if [[ -n "${effective_branch}" ]]; then
    echo "Checking out branch '${effective_branch}' in ${target_path}"
    if branch_exists_local "${target_path}" "${effective_branch}"; then
      git -C "${target_path}" checkout "${effective_branch}"
    else
      git -C "${target_path}" checkout -b "${effective_branch}" --track "origin/${effective_branch}"
    fi
    git -C "${target_path}" pull --ff-only origin "${effective_branch}"
    git -C "${target_path}" submodule update --init --recursive
  else
    echo "WARN: No branch resolved for ${target_path}. Keeping current HEAD."
  fi
}

generate_eclipse_metadata_for_repo() {
  local repo_path="$1"
  local gradlew=""

  if [[ -x "${repo_path}/gradlew" ]]; then
    gradlew="${repo_path}/gradlew"
  else
    local child
    while IFS= read -r -d '' child; do
      gradlew="${child}"
      break
    done < <(find "${repo_path}" -mindepth 2 -maxdepth 2 -type f -name gradlew -perm -u+x -print0 2>/dev/null)
  fi

  if [[ -z "${gradlew}" ]]; then
    echo "WARN: No executable gradlew found in ${repo_path}. Skipping Eclipse metadata generation."
    return
  fi

  local workdir
  workdir="$(dirname "${gradlew}")"
  echo "Generating Eclipse metadata via ${gradlew}"
  (cd "${workdir}" && ./gradlew -q eclipse)
}

run_docker_import() {
  local was_running=0

  if docker compose ps --status running --services | grep -qx "${COMPOSE_SERVICE}"; then
    was_running=1
    echo "Stopping running compose service '${COMPOSE_SERVICE}' for workspace import..."
    REPOS_DIR="${REPOS_DIR}" WORKSPACE_DIR="${WORKSPACE_DIR}" docker compose stop "${COMPOSE_SERVICE}"
  fi

  echo "Running headless Eclipse import in one-off container..."
  REPOS_DIR="${REPOS_DIR}" WORKSPACE_DIR="${WORKSPACE_DIR}" docker compose run --rm --no-deps --entrypoint bash "${COMPOSE_SERVICE}" -lc '
set -euo pipefail
mkdir -p /workspace
if [ -f /workspace/.metadata/.lock ]; then
  echo "WARN: Removing stale workspace lock: /workspace/.metadata/.lock"
  rm -f /workspace/.metadata/.lock
fi
mapfile -t project_dirs < <(find /repos -type f -name .project -printf "%h\n" | sort -u)
if [ "${#project_dirs[@]}" -eq 0 ]; then
  echo "No .project files found under /repos. Nothing to import."
  exit 0
fi
launcher="/opt/eclipse/eclipse"
if [ -x /opt/eclipse/eclipsec ]; then
  launcher="/opt/eclipse/eclipsec"
fi
if ! command -v xvfb-run >/dev/null 2>&1; then
  echo "ERROR: xvfb-run not found in container image." >&2
  exit 1
fi
echo "Importing ${#project_dirs[@]} Eclipse projects into /workspace"
batch_size=20
for ((i=0; i<${#project_dirs[@]}; i+=batch_size)); do
  end=$((i+batch_size))
  if [ "${end}" -gt "${#project_dirs[@]}" ]; then end="${#project_dirs[@]}"; fi
  args=(-nosplash -consoleLog -data /workspace)
  for ((j=i; j<end; j++)); do
    args+=(-import "${project_dirs[j]}")
  done
  timeout 180 xvfb-run -a "${launcher}" "${args[@]}" -vmargs \
    --add-opens=java.base/java.util=ALL-UNNAMED \
    --add-opens=java.base/java.lang=ALL-UNNAMED \
    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
    --add-opens=java.base/java.text=ALL-UNNAMED \
    --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
  code=$?
  if [ "${code}" -eq 124 ]; then
    echo "ERROR: Eclipse import batch timed out after 180s. See /workspace/.metadata/.log" >&2
    exit 1
  fi
done
'

  if [[ "${was_running}" -eq 1 ]]; then
    echo "Restarting compose service '${COMPOSE_SERVICE}'..."
    REPOS_DIR="${REPOS_DIR}" WORKSPACE_DIR="${WORKSPACE_DIR}" docker compose up -d "${COMPOSE_SERVICE}"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --master-repo-url) MASTER_REPO_URL="$2"; shift 2;;
    --master-branch) MASTER_BRANCH="$2"; shift 2;;
    --master-target-dir) MASTER_TARGET_DIR="$2"; shift 2;;
    --sub-repo-url1) SUB_REPO_URL1="$2"; shift 2;;
    --sub-branch1) SUB_BRANCH1="$2"; shift 2;;
    --sub-target-dir1) SUB_TARGET_DIR1="$2"; shift 2;;
    --sub-repo-url2) SUB_REPO_URL2="$2"; shift 2;;
    --sub-branch2) SUB_BRANCH2="$2"; shift 2;;
    --sub-target-dir2) SUB_TARGET_DIR2="$2"; shift 2;;
    --skip-sync) SKIP_SYNC=1; shift;;
    --generate-eclipse-projects) GENERATE_ECLIPSE_PROJECTS=1; shift;;
    --import-into-eclipse) IMPORT_INTO_ECLIPSE=1; shift;;
    --compose-service) COMPOSE_SERVICE="$2"; shift 2;;
    --repos-dir) REPOS_DIR="$2"; shift 2;;
    --workspace-dir) WORKSPACE_DIR="$2"; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1;;
  esac
done

if [[ -z "${MASTER_REPO_URL}" ]]; then
  echo "ERROR: --master-repo-url is required" >&2
  usage
  exit 1
fi

if [[ -z "${MASTER_TARGET_DIR}" ]]; then
  MASTER_TARGET_DIR="$(default_target_dir "${MASTER_REPO_URL}")"
fi
if [[ -n "${SUB_REPO_URL1}" && -z "${SUB_TARGET_DIR1}" ]]; then
  SUB_TARGET_DIR1="$(default_target_dir "${SUB_REPO_URL1}")"
fi
if [[ -n "${SUB_REPO_URL2}" && -z "${SUB_TARGET_DIR2}" ]]; then
  SUB_TARGET_DIR2="$(default_target_dir "${SUB_REPO_URL2}")"
fi

write_manifest

if [[ "${SKIP_SYNC}" -eq 0 ]]; then
  clone_or_update_repo "${MASTER_REPO_URL}" "${MASTER_BRANCH}" "${MASTER_TARGET_DIR}"
  if [[ -n "${SUB_REPO_URL1}" ]]; then
    clone_or_update_repo "${SUB_REPO_URL1}" "${SUB_BRANCH1}" "${SUB_TARGET_DIR1}"
  fi
  if [[ -n "${SUB_REPO_URL2}" ]]; then
    clone_or_update_repo "${SUB_REPO_URL2}" "${SUB_BRANCH2}" "${SUB_TARGET_DIR2}"
  fi
fi

if [[ "${GENERATE_ECLIPSE_PROJECTS}" -eq 1 ]]; then
  generate_eclipse_metadata_for_repo "${REPOS_DIR}/${MASTER_TARGET_DIR}"
  [[ -n "${SUB_REPO_URL1}" ]] && generate_eclipse_metadata_for_repo "${REPOS_DIR}/${SUB_TARGET_DIR1}"
  [[ -n "${SUB_REPO_URL2}" ]] && generate_eclipse_metadata_for_repo "${REPOS_DIR}/${SUB_TARGET_DIR2}"
fi

if [[ "${IMPORT_INTO_ECLIPSE}" -eq 1 ]]; then
  run_docker_import
fi

echo "Done. Repositories are managed via: ${REPO_ROOT}/repos-manifest.txt"
